apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadyfck6857-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadyfck6857-tenant-component
    app.kubernetes.io/part-of: loadyfck6857-tenant-app
  name: loadyfck6857-tenant-component
  namespace: loadyfck6857-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadyfck6857-tenant-component
    weight: null
status: {}
